---
apiVersion: v1
kind: Template
labels:
  template: imagestream-generic
metadata:
  name: imagestream-generic
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    labels:
      role: ${IMAGE_STREAM_ROLE}
    name: ${IMAGE_STREAM_NAME}
    namespace: ${IMAGE_STREAM_NAMESPACE}
  spec:
    tags:
    - from:
        kind: ${IMAGE_STREAM_TAG_FROM_KIND}
        name: ${IMAGE_STREAM_TAG_FROM_NAME}
      name: ${IMAGE_STEAM_TAG_VERSION}
parameters:
- name: IMAGE_STREAM_NAME
  description: The name of the ImageStream
  displayName: ImageSteam Name
  required: true
- name: IMAGE_STREAM_ROLE
  description: The role of the ImageStream
  displayName: ImageSteam Role (optional)
  value: generic-imagestream
- name: IMAGE_STREAM_TAG_FROM_NAME
  description: The name of the ImageStream
  displayName: ImageSteam Tag From Name
  required: true
- name: IMAGE_STREAM_TAG_VERSION
  description: The Version of the ImageStream
  displayName: ImageSteam Tag Version
  value: latest
- name: IMAGE_STREAM_TAG_FROM_KIND
  description: The kind of the ImageStream
  displayName: ImageSteam Tag From Kind
  value: Docker

