apiVersion: v1
kind: Template
labels:
  template: secret-generic-opaque
  credential.sync.jenkins.openshift.io: 'true'
metadata:
  name: secret-generic-opaque
objects:
- apiVersion: v1
  type: Opaque
  data:
    ${FILE_NAME}: ${SECRET_VALUE}
  kind: Secret
  metadata:
    labels:
      credential.sync.jenkins.openshift.io: true
    name: ${SECRET_NAME}
parameters:
- description: The filename of the secret
  displayName: The filename of the secret
  name: FILE_NAME
  required: true
- description: The name for the newly created secret
  displayName: Secret name
  name: SECRET_NAME
  required: true
- description: Base64 encoding of the file
  displayName: Secret value
  name: SECRET_VALUE
  required: true